In [2]:
import pandas as pd
import numpy as np
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: f:\Mystic\Python\Pandas\movies.csv

  0%|          | 0.00/112k [00:00<?, ?B/s]
100%|██████████| 112k/112k [00:00<00:00, 510kB/s]
100%|██████████| 112k/112k [00:00<00:00, 510kB/s]

In [3]:
!gdown 1Ws-_s1fHZ9HfGLVUQurbHDvStePlEJm

Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1Ws-_s1fHZ9HfGLVUQurbHDvStePlEJm

but Gdown can't. Please check connections and permissions.

In [4]:
movies = pd.read_csv("movies.csv")
movies

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [5]:
!gdown 173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ

Downloading...
From: https://drive.google.com/uc?id=173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ
To: f:\Mystic\Python\Pandas\Pfizer_1.csv

  0%|          | 0.00/1.51k [00:00<?, ?B/s]
100%|██████████| 1.51k/1.51k [00:00<?, ?B/s]

In [7]:
data = pd.read_csv("Pfizer_1.csv")
data

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       18 non-null     object
 1   Drug_Name  18 non-null     object
 2   Parameter  18 non-null     object
 3   1:30:00    16 non-null     float64
 4   2:30:00    16 non-null     float64
 5   3:30:00    12 non-null     float64
 6   4:30:00    14 non-null     float64
 7   5:30:00    16 non-null     float64
 8   6:30:00    18 non-null     int64
 9   7:30:00    16 non-null     float64
 10  8:30:00    14 non-null     float64
 11  9:30:00    16 non-null     float64
 12  10:30:00   18 non-null     int64
 13  11:30:00   16 non-null     float64
 14  12:30:00   18 non-null     int64
dtypes: float64(9), int64(3), object(3)
memory usage: 2.2+ KB

In [10]:
pd.melt(data,id_vars=["Date","Drug_Name","Parameter"])

           Date                Drug_Name    Parameter  variable  value
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00   23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00   12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00    NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00    NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00   24.0
..          ...                      ...          ...       ...    ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00   14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00   23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00   28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00   24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00   15.0

[216 rows x 5 columns]

In [16]:
new_data_melt = pd.melt(data,id_vars=["Date","Drug_Name","Parameter"],var_name="Time",value_name="Measurement")
new_data_melt

           Date                Drug_Name    Parameter      Time  Measurement
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00         23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00         12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00          NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00          NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00         24.0
..          ...                      ...          ...       ...          ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00         14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00         23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00         28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00         24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00         15.0

[216 rows x 5 columns]

In [17]:
new_data_pivot = pd.pivot(new_data,index=["Date","Drug_Name","Parameter"],columns="Time",values="Measurement")
new_data_pivot

Time                                            10:30:00  11:30:00  12:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure         18.0      19.0      20.0
                                   Temperature      20.0      20.0      21.0
           docetaxel injection     Pressure         26.0      29.0      28.0
                                   Temperature      23.0      25.0      25.0
           ketamine hydrochloride  Pressure          9.0       9.0      11.0
                                   Temperature      22.0      21.0      20.0
16-10-2020 diltiazem hydrochloride Pressure         24.0       NaN      27.0
                                   Temperature      40.0       NaN      42.0
           docetaxel injection     Pressure         28.0      29.0      30.0
                                   Temperature      56.0      57.0      58.0
           ketamine hydrochloride  Pressure         16.0      17.0      18.0
                                   Temperature      13.0      14.0      15.0
17-10-2020 diltiazem hydrochloride Pressure         11.0      13.0      14.0
                                   Temperature      14.0      11.0      10.0
           docetaxel injection     Pressure         28.0      29.0      28.0
                                   Temperature      21.0      22.0      23.0
           ketamine hydrochloride  Pressure         13.0      14.0      15.0
                                   Temperature      22.0      23.0      24.0

Time                                            1:30:00  2:30:00  3:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        12.0     13.0      NaN
                                   Temperature     23.0     22.0      NaN
           docetaxel injection     Pressure         NaN     22.0     22.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         8.0      NaN      NaN
                                   Temperature     24.0      NaN      NaN
16-10-2020 diltiazem hydrochloride Pressure        18.0     19.0     20.0
                                   Temperature     34.0     35.0     36.0
           docetaxel injection     Pressure        23.0     24.0      NaN
                                   Temperature     46.0     47.0      NaN
           ketamine hydrochloride  Pressure        12.0     12.0     13.0
                                   Temperature      8.0      9.0     10.0
17-10-2020 diltiazem hydrochloride Pressure         3.0      4.0      4.0
                                   Temperature     20.0     19.0     19.0
           docetaxel injection     Pressure        20.0     22.0     22.0
                                   Temperature     12.0     13.0     14.0
           ketamine hydrochloride  Pressure         8.0      9.0     10.0
                                   Temperature     13.0     14.0     15.0

Time                                            4:30:00  5:30:00  6:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        11.0     13.0     14.0
                                   Temperature     21.0     21.0     22.0
           docetaxel injection     Pressure         NaN     22.0     23.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         7.0      NaN      9.0
                                   Temperature     27.0      NaN     26.0
16-10-2020 diltiazem hydrochloride Pressure        21.0     22.0     23.0
                                   Temperature     36.0     37.0     38.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     48.0     48.0     49.0
           ketamine hydrochloride  Pressure         NaN     15.0     15.0
                                   Temperature      NaN     11.0     12.0
17-10-2020 diltiazem hydrochloride Pressure         4.0      6.0      8.0
                                   Temperature     18.0     17.0     16.0
           docetaxel injection     Pressure        22.0     22.0     23.0
                                   Temperature     15.0     16.0     17.0
           ketamine hydrochloride  Pressure        11.0     11.0     12.0
                                   Temperature     16.0     17.0     18.0

Time                                            7:30:00  8:30:00  9:30:00
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        16.0     16.0     24.0
                                   Temperature     23.0     21.0     22.0
           docetaxel injection     Pressure         NaN      NaN     27.0
                                   Temperature      NaN      NaN     23.0
           ketamine hydrochloride  Pressure        10.0     11.0     10.0
                                   Temperature     25.0     24.0     23.0
16-10-2020 diltiazem hydrochloride Pressure        24.0     25.0     25.0
                                   Temperature     37.0     38.0     39.0
           docetaxel injection     Pressure        28.0     29.0     28.0
                                   Temperature     50.0     52.0     55.0
           ketamine hydrochloride  Pressure        15.0     15.0      NaN
                                   Temperature     12.0     11.0      NaN
17-10-2020 diltiazem hydrochloride Pressure         9.0      NaN      9.0
                                   Temperature     15.0      NaN     13.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     18.0     19.0     20.0
           ketamine hydrochloride  Pressure        12.0     11.0     12.0
                                   Temperature     19.0     20.0     21.0

In [19]:
new_data_melt

           Date                Drug_Name    Parameter      Time  Measurement
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00         23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00         12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00          NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00          NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00         24.0
..          ...                      ...          ...       ...          ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00         14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00         23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00         28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00         24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00         15.0

[216 rows x 5 columns]

In [22]:
final = pd.pivot(new_data_melt,index=["Date","Drug_Name","Time"],columns="Parameter",values="Measurement")
final

Parameter                                    Pressure  Temperature
Date       Drug_Name               Time
15-10-2020 diltiazem hydrochloride 10:30:00      18.0         20.0
                                   11:30:00      19.0         20.0
                                   12:30:00      20.0         21.0
                                   1:30:00       12.0         23.0
                                   2:30:00       13.0         22.0
...                                               ...          ...
17-10-2020 ketamine hydrochloride  5:30:00       11.0         17.0
                                   6:30:00       12.0         18.0
                                   7:30:00       12.0         19.0
                                   8:30:00       11.0         20.0
                                   9:30:00       12.0         21.0

[108 rows x 2 columns]

In [23]:
final.reset_index()#reset index will make our data look tidy and arrange it in a proper format

Parameter,Date,Drug_Name,Time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0
...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0

In [25]:
final.reset_index().head(20)

Parameter,Date,Drug_Name,Time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0
5,15-10-2020,diltiazem hydrochloride,3:30:00,NaN,NaN
6,15-10-2020,diltiazem hydrochloride,4:30:00,11.0,21.0
7,15-10-2020,diltiazem hydrochloride,5:30:00,13.0,21.0
8,15-10-2020,diltiazem hydrochloride,6:30:00,14.0,22.0
9,15-10-2020,diltiazem hydrochloride,7:30:00,16.0,23.0
10,15-10-2020,diltiazem hydrochloride,8:30:00,16.0,21.0
11,15-10-2020,diltiazem hydrochloride,9:30:00,24.0,22.0
12,15-10-2020,docetaxel injection,10:30:00,26.0,23.0
13,15-10-2020,docetaxel injection,11:30:00,29.0,25.0
14,15-10-2020,docetaxel injection,12:30:00,28.0,25.0
15,15-10-2020,docetaxel injection,1:30:00,NaN,NaN
16,15-10-2020,docetaxel injection,2:30:00,22.0,17.0
17,15-10-2020,docetaxel injection,3:30:00,22.0,18.0
18,15-10-2020,docetaxel injection,4:30:00,NaN,NaN
19,15-10-2020,docetaxel injection,5:30:00,22.0,17.0

In [41]:
pd.pivot_table(data=final
               ,index="Drug_Name",columns="Date",values=["Pressure","Temperature"],aggfunc={"Pressure":"mean","Temperature":"min"})

KeyError: "['Drug_Name'] not in index"