In [1]:
import pandas as pd
df = pd.read_csv("dataset_1.csv")

In [2]:
df.head(10)

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,SC60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Feb,2008,WD,Normal,208500
1,1,SC20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,May,2007,WD,Normal,181500
2,2,SC60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Sep,2008,WD,Normal,223500
3,3,SC70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Feb,2006,WD,Abnorml,140000
4,4,SC60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Dec,2008,WD,Normal,250000
5,5,SC50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,No,MnPrv,Shed,700,Oct,2009,WD,Normal,143000
6,6,SC20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Aug,2007,WD,Normal,307000
7,7,SC60,RL,0.0,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,Shed,350,Nov,2009,WD,Normal,200000
8,8,SC50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Apr,2008,WD,Abnorml,129900
9,9,SC190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Jan,2008,WD,Normal,118000

RENAMING COLUMNS

In [3]:
df.columns

Index(['Unnamed: 0', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea',
       'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [4]:
df.nunique()

Unnamed: 0       1460
MSSubClass         15
MSZoning            5
LotFrontage       111
LotArea          1073
                 ...
MoSold             12
YrSold              5
SaleType            9
SaleCondition       6
SalePrice         663
Length: 81, dtype: int64

In [7]:
df.rename({"MSSubClass" : "MS_Sub_class"},axis=1)#this will not make changes in original dataframe
df.rename({"MSSubClass" : "MS_Sub_class"},axis=1,inplace="True")#this will make changes in original dataframe
df

,Unnamed: 0,MS_Sub_class,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,SC60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Feb,2008,WD,Normal,208500
1,1,SC20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,May,2007,WD,Normal,181500
2,2,SC60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Sep,2008,WD,Normal,223500
3,3,SC70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Feb,2006,WD,Abnorml,140000
4,4,SC60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Dec,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,SC60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Aug,2007,WD,Normal,175000
1456,1456,SC20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,No,MnPrv,No,0,Feb,2010,WD,Normal,210000
1457,1457,SC70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,No,GdPrv,Shed,2500,May,2010,WD,Normal,266500
1458,1458,SC20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Apr,2010,WD,Normal,142125
1459,1459,SC20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Jun,2008,WD,Normal,147500

In [9]:
df["Sales-1000"] = df["SalePrice"]-1000#it will take all the corresponding values of the SalesPrice and will perform operation as provided
 
df

,Unnamed: 0,MS_Sub_class,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Sales-1000
0,0,SC60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,No,No,No,0,Feb,2008,WD,Normal,208500,207500
1,1,SC20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,No,No,No,0,May,2007,WD,Normal,181500,180500
2,2,SC60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,No,No,No,0,Sep,2008,WD,Normal,223500,222500
3,3,SC70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,No,No,No,0,Feb,2006,WD,Abnorml,140000,139000
4,4,SC60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,No,No,No,0,Dec,2008,WD,Normal,250000,249000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,SC60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,No,No,No,0,Aug,2007,WD,Normal,175000,174000
1456,1456,SC20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,No,MnPrv,No,0,Feb,2010,WD,Normal,210000,209000
1457,1457,SC70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,No,GdPrv,Shed,2500,May,2010,WD,Normal,266500,265500
1458,1458,SC20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,No,No,No,0,Apr,2010,WD,Normal,142125,141125
1459,1459,SC20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,No,No,No,0,Jun,2008,WD,Normal,147500,146500

ROW-VISE OPERATIONS

In [3]:
#indexing 
import numpy as np
df.index = np.arange(1,df.shape[0]+1,dtype='int')
df

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1,0,SC60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Feb,2008,WD,Normal,208500
2,1,SC20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,May,2007,WD,Normal,181500
3,2,SC60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Sep,2008,WD,Normal,223500
4,3,SC70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Feb,2006,WD,Abnorml,140000
5,4,SC60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Dec,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,1455,SC60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Aug,2007,WD,Normal,175000
1457,1456,SC20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,No,MnPrv,No,0,Feb,2010,WD,Normal,210000
1458,1457,SC70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,No,GdPrv,Shed,2500,May,2010,WD,Normal,266500
1459,1458,SC20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Apr,2010,WD,Normal,142125
1460,1459,SC20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Jun,2008,WD,Normal,147500

In [4]:
df.loc[1:4]

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1,0,SC60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,Feb,2008,WD,Normal,208500
2,1,SC20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,No,No,No,0,May,2007,WD,Normal,181500
3,2,SC60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Sep,2008,WD,Normal,223500
4,3,SC70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,No,No,No,0,Feb,2006,WD,Abnorml,140000

In [6]:
temp = df.set_index("LotFrontage")
temp

,Unnamed: 0,MSSubClass,MSZoning,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
LotFrontage,,,,,,,,,,,,,,,,,,,,,
65.0,0,SC60,RL,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Feb,2008,WD,Normal,208500
80.0,1,SC20,RL,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,No,No,No,0,May,2007,WD,Normal,181500
68.0,2,SC60,RL,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,No,No,No,0,Sep,2008,WD,Normal,223500
60.0,3,SC70,RL,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,No,No,No,0,Feb,2006,WD,Abnorml,140000
84.0,4,SC60,RL,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,No,No,No,0,Dec,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62.0,1455,SC60,RL,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Aug,2007,WD,Normal,175000
85.0,1456,SC20,RL,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,MnPrv,No,0,Feb,2010,WD,Normal,210000
66.0,1457,SC70,RL,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,GdPrv,Shed,2500,May,2010,WD,Normal,266500
68.0,1458,SC20,RL,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Apr,2010,WD,Normal,142125
75.0,1459,SC20,RL,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Jun,2008,WD,Normal,147500

In [7]:
temp.loc[68.0]#scince the indices are in float so i have provided float and these are explicit indices

,Unnamed: 0,MSSubClass,MSZoning,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
LotFrontage,,,,,,,,,,,,,,,,,,,,,
68.0,2,SC60,RL,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,No,No,No,0,Sep,2008,WD,Normal,223500
68.0,38,SC20,RL,7922,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Jan,2010,WD,Abnorml,109000
68.0,53,SC20,RL,50271,Pave,NaN,IR1,Low,AllPub,Inside,...,0,No,No,No,0,Nov,2006,WD,Normal,385000
68.0,192,SC20,RL,9017,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,No,No,No,0,Sep,2009,WD,Normal,192000
68.0,257,SC20,RL,8814,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Mar,2009,WD,Abnorml,220000
68.0,350,SC120,RL,7820,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,No,No,No,0,Dec,2007,New,Partial,318061
68.0,395,SC20,RL,9571,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Jun,2010,WD,Normal,129000
68.0,410,SC20,RL,9571,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Jun,2009,COD,Abnorml,60000
68.0,756,SC60,RL,10769,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,No,No,No,0,Apr,2009,WD,Normal,212000
68.0,978,SC20,RL,9450,Pave,NaN,Reg,Bnk,AllPub,Inside,...,0,No,No,No,0,May,2007,WD,Abnorml,110000
68.0,985,SC190,RL,10880,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Aug,2008,ConLD,Normal,125000
68.0,993,SC60,RL,8846,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Aug,2006,New,Partial,173900
68.0,1053,SC20,RL,8562,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,May,2010,WD,Normal,144500
68.0,1188,SC60,RL,8935,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,No,No,No,0,Jul,2009,WD,Normal,195000
68.0,1216,SC90,RM,8930,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Apr,2010,WD,Normal,112000
68.0,1311,SC20,RL,8814,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Jan,2007,New,Partial,203000
68.0,1366,SC60,RL,9179,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,No,No,No,0,Jun,2008,WD,Abnorml,193000
68.0,1392,SC85,RL,7838,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,MnWw,No,0,Dec,2006,WD,Normal,123000
68.0,1458,SC20,RL,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,No,No,No,0,Apr,2010,WD,Normal,142125

In [12]:
temp.reset_index(inplace=True)
new = temp.head()

In [13]:
new

,level_0,index,LotFrontage,Unnamed: 0,MSSubClass,MSZoning,LotArea,Street,Alley,LotShape,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,0,65.0,0,SC60,RL,8450,Pave,NaN,Reg,...,0,No,No,No,0,Feb,2008,WD,Normal,208500
1,1,1,80.0,1,SC20,RL,9600,Pave,NaN,Reg,...,0,No,No,No,0,May,2007,WD,Normal,181500
2,2,2,68.0,2,SC60,RL,11250,Pave,NaN,IR1,...,0,No,No,No,0,Sep,2008,WD,Normal,223500
3,3,3,60.0,3,SC70,RL,9550,Pave,NaN,IR1,...,0,No,No,No,0,Feb,2006,WD,Abnorml,140000
4,4,4,84.0,4,SC60,RL,14260,Pave,NaN,IR1,...,0,No,No,No,0,Dec,2008,WD,Normal,250000

In [ ]:
new.columns